parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: source
        connections:
            source:
                url: '%env(resolve:SOURCE_DATABASE_URL)%'
            target:
                options:
                    !php/const PDO::MYSQL_ATTR_LOCAL_INFILE: 1
                url: '%env(resolve:TARGET_DATABASE_URL)%'
