old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    fogger_data_chunks:
      connection:       default
      exchange_options: { name: 'fogger::data_chunks', type: direct }
      queue_options:    { name: 'fogger::data_chunks'}
  consumers:
    fogger_data_chunks:
      connection:       default
      exchange_options: { name: 'fogger::data_chunks', type: direct }
      queue_options:    { name: 'fogger::data_chunks'}
      callback:         App\Fogger\Data\ChunkConsumer
