version: '2.0'
services:
  postgres_test_source:
    environment:
      POSTGRES_DB: source
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    image: postgres
  postgres_test_target:
    environment:
      POSTGRES_DB: target
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    image: postgres
  app:
    environment:
      SOURCE_DATABASE_URL: postgresql://user:pass@postgres_test_source:5432/source
      TARGET_DATABASE_URL: postgresql://user:pass@postgres_test_target:5432/target
